//Games Information Actions
const SET_GAMES_INFO = "SET_GAMES_INFO";
const SET_LEADERBOARD_INFO = "SET_LEADERBOARD_INFO";

//Gameplay Info
const SET_GAME_STATE_INFO = "SET_GAME_STATE_INFO";
const SET_GAME_VIEW_INFO = "SET_GAME_VIEW_INFO";
const CLEAR_GAME_VIEW_INFO = "CLEAR_GAME_VIEW_INFO";

export {
  SET_GAMES_INFO,
  SET_LEADERBOARD_INFO,
  SET_GAME_STATE_INFO,
  SET_GAME_VIEW_INFO,
  CLEAR_GAME_VIEW_INFO
};
